module.exports = {
    name: 'EssentialsX',
    description: 'Best utility plugin for your server.',
    pluginId: 'EssentialsX',
    mavenIntegration: `
        <repositories>
            <repository>
                <id>essentials-releases</id>
                <url>https://repo.essentialsx.net/releases/</url>
            </repository>
        </repositories>
        <dependencies>
            <dependency>
                <groupId>net.essentialsx</groupId>
                <artifactId>EssentialsX</artifactId>
                <version>2.21.1</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    
    `,
    usage: `
        The main class is IEssentials class: net.ess3.api.
        
        Get the main class:
        IEssentials essentials = (IEssentials) Bukkit.getPluginManager().getPlugin("EssentialsX");
        
        IEssentials class: net.ess3.api (extends com.earth2me.essentials.IEssentials)
        Instance Methods
        Collection<String> getVanishedPlayersNew()
        CustomItemResolver getCustomItemResolver()
        void addReloadListener(IConf var1)
        void reload()
        Map<String, IEssentialsCommand> getCommandMap()
        List<String> onTabCompleteEssentials(CommandSender var1, Command var2, String var3, String[] var4, ClassLoader var5, String var6, String var7, IEssentialsModule var8)
        boolean onCommandEssentials(CommandSender var1, Command var2, String var3, String[] var4, ClassLoader var5, String var6, String var7, IEssentialsModule var8)
        User getUser(Object var1) (deprecated)
        User getUser(UUID var1)
        User getUser(String var1)
        User getUser(Player var1)
        User matchUser(Server var1, User var2, String var3, Boolean var4, boolean var5)
        boolean canInteractWith(CommandSource var1, User var2)
        boolean canInteractWith(User var1, User var2)
        I18n getI18n()
        User getOfflineUser(String var1)
        World getWorld(String var1)
        int broadcastMessage(String var1)
        int broadcastMessage(IUser var1, String var2)
        int broadcastMessage(IUser var1, String var2, Predicate<IUser> var3)
        int broadcastMessage(String var1, String var2)
        void broadcastTl(String var1, Object... var2)
        void broadcastTl(IUser var1, String var2, Object... var3)
        void broadcastTl(IUser var1, String var2, String var3, Object... var4)
        void broadcastTl(IUser var1, Predicate<IUser> var2, String var3, Object... var4)
        void broadcastTl(IUser var1, Predicate<IUser> var2, boolean var3, String var4, Object... var5)
        ISettings getSettings()
        BukkitScheduler getScheduler()
        IJails getJails()
        IWarps getWarps()
        Worth getWorth()
        Backup getBackup()
        Kits getKits()
        RandomTeleport getRandomTeleport()
        UpdateChecker getUpdateChecker()
        BukkitTask runTaskAsynchronously(Runnable var1)
        BukkitTask runTaskLaterAsynchronously(Runnable var1, long var2)
        BukkitTask runTaskTimerAsynchronously(Runnable var1, long var2, long var3)
        int scheduleSyncDelayedTask(Runnable var1)
        int scheduleSyncDelayedTask(Runnable var1, long var2)
        int scheduleSyncRepeatingTask(Runnable var1, long var2, long var3)
        PermissionsHandler getPermissionsHandler()
        AlternativeCommandsHandler getAlternativeCommandsHandler()
        void showError(CommandSource var1, Throwable var2, String var3)
        IItemDb getItemDb()
        IUserMap getUsers()
        UserMap getUserMap() (deprecated)
        BalanceTop getBalanceTop()
        EssentialsTimer getTimer()
        MailService getMail()
        List<String> getVanishedPlayers() (deprecated)
        Collection<Player> getOnlinePlayers()
        Iterable<User> getOnlineUsers()
        PluginCommand getPluginCommand(String var1)
        ProviderFactory getProviders()
    II18n class: net.ess3.api (extends com.earth2me.essentials.api.II18n)
        Instance Methods
        Locale getCurrentLocale()
    IItemDb class: net.ess3.api (extends com.earth2me.essentials.api.IItemDb)
        Instance Methods
        void registerResolver(Plugin var1, String var2, IItemDb.ItemResolver var3)
        void unregisterResolver(Plugin var1, String var2)
        boolean isResolverPresent(Plugin var1, String var2)
        Map<PluginKey, IItemDb.ItemResolver> getResolvers()
        Map<PluginKey, IItemDb.ItemResolver> getResolvers(Plugin var1)
        IItemDb.ItemResolver getResolver(Plugin var1, String var2)
        ItemStack get(String var1, boolean var2)
        String serialize(ItemStack var1, boolean var2) (deprecated)
        ItemStack get(String var1, int var2) (default)
        ItemStack get(String var1)
        String names(ItemStack var1) (default)
        List<String> nameList(ItemStack var1)
        String name(ItemStack var1)
        List<ItemStack> getMatching(User var1, String[] var2)
        String serialize(ItemStack var1)
        Collection<String> listNames()
        Material getFromLegacyId(int var1) (deprecated, default)
        int getLegacyId(Material var1) (deprecated)
        Material getFromLegacy(String var1) (default)
        Material getFromLegacy(int var1, byte var2) (default)
        boolean isReady()
    IJails class: net.ess3.api (extends com.earth2me.essentials.api.IJails)
        Instance Methods
        Location getJail(String var1)
        Collection<String> getList()
        int getCount()
        void removeJail(String var1)
        void sendToJail(IUser var1, String var2, CompletableFuture<Boolean> var3)
        void setJail(String var1, Location var2)
        void startTransaction()
        void stopTransaction(boolean var1)
    ISettings class: net.ess3.api (extends com.earth2me.essentials.ISettings)
        Instance Methods
        File getConfigFile()
        boolean areSignsDisabled()
        IText getAnnounceNewPlayerFormat()
        boolean getAnnounceNewPlayers()
        String getNewPlayerKit()
        String getBackupCommand()
        long getBackupInterval()
        boolean isAlwaysRunBackup()
        String getChatFormat(String var1)
        String getChatFormat(String var1, ChatType var2)
        String getWorldAlias(String var1)
        int getChatRadius()
        int getNearRadius()
        char getChatShout()
        char getChatQuestion()
        boolean isShoutDefault()
        boolean isPersistShout()
        boolean isChatQuestionEnabled()
        boolean isUsePaperChatEvent()
        BigDecimal getCommandCost(IEssentialsCommand var1)
        BigDecimal getCommandCost(String var1)
        String getCurrencySymbol()
        boolean isCurrencySymbolSuffixed()
        int getOversizedStackSize()
        int getDefaultStackSize()
        double getHealCooldown()
        Set<String> getSocialSpyCommands()
        boolean getSocialSpyListenMutedPlayers()
        boolean isSocialSpyMessages()
        boolean isSocialSpyDisplayNames()
        Set<String> getMuteCommands()
        CommentedConfigurationNode getKitSection() (deprecated)
        boolean isSkippingUsedOneTimeKitsFromKitList()
        String getLocale()
        boolean isPerPlayerLocale()
        String getNewbieSpawn()
        String getNicknamePrefix()
        String getOperatorColor()
        boolean getPerWarpPermission()
        boolean getProtectBoolean(String var1, boolean var2)
        int getProtectCreeperMaxHeight()
        List<Material> getProtectList(String var1)
        List<String> getProtectListRaw(String var1)
        boolean getProtectPreventSpawn(String var1)
        String getProtectString(String var1)
        boolean getRespawnAtHome()
        String getRandomSpawnLocation()
        String getRandomRespawnLocation()
        boolean isRespawnAtAnchor()
        Set getMultipleHomes()
        int getHomeLimit(String var1)
        int getHomeLimit(User var1)
        int getSpawnMobLimit()
        BigDecimal getStartingBalance()
        boolean isTeleportSafetyEnabled()
        boolean isForceDisableTeleportSafety()
        boolean isAlwaysTeleportSafety()
        boolean isTeleportPassengerDismount()
        boolean isForcePassengerTeleport()
        double getTeleportCooldown()
        double getTeleportDelay()
        boolean hidePermissionlessHelp()
        boolean isCommandDisabled(IEssentialsCommand var1)
        boolean isCommandDisabled(String var1)
        Set<String> getDisabledCommands()
        boolean isVerboseCommandUsages()
        boolean isCommandOverridden(String var1)
        boolean isDebug()
        void setDebug(boolean var1)
        boolean isEcoDisabled()
        boolean isTradeInStacks(int var1) (deprecated)
        boolean isTradeInStacks(Material var1)
        List<Material> itemSpawnBlacklist()
        List<EssentialsSign> enabledSigns()
        boolean permissionBasedItemSpawn()
        boolean showNonEssCommandsInHelp()
        boolean warnOnBuildDisallow()
        boolean warnOnSmite()
        BigDecimal getMaxMoney()
        BigDecimal getMinMoney()
        boolean isEcoLogEnabled()
        boolean isEcoLogUpdateEnabled()
        boolean realNamesOnList()
        boolean removeGodOnDisconnect()
        boolean changeDisplayName()
        boolean changePlayerListName()
        boolean changeTabCompleteName()
        boolean isPlayerCommand(String var1)
        boolean useBukkitPermissions()
        boolean addPrefixSuffix()
        boolean disablePrefix()
        boolean disableSuffix()
        long getAutoAfk()
        long getAutoAfkKick()
        boolean getFreezeAfkPlayers()
        boolean cancelAfkOnMove()
        boolean cancelAfkOnInteract()
        boolean cancelAfkOnChat()
        boolean sleepIgnoresAfkPlayers()
        boolean sleepIgnoresVanishedPlayers()
        boolean isAfkListName()
        String getAfkListName()
        boolean broadcastAfkMessage()
        boolean areDeathMessagesEnabled()
        ISettings.KeepInvPolicy getVanishingItemsPolicy()
        ISettings.KeepInvPolicy getBindingItemsPolicy()
        int getJoinQuitMessagePlayerCount()
        boolean hasJoinQuitMessagePlayerCount()
        Set<String> getNoGodWorlds()
        boolean getUpdateBedAtDaytime()
        boolean allowUnsafeEnchantments()
        boolean getRepairEnchanted()
        boolean isWorldTeleportPermissions()
        boolean isWorldHomePermissions()
        int getMaxTreeCommandRange()
        boolean registerBackInListener()
        boolean getDisableItemPickupWhileAfk()
        EventPriority getRespawnPriority()
        EventPriority getSpawnJoinPriority()
        long getTpaAcceptCancellation()
        int getTpaMaxRequests()
        long getTeleportInvulnerability()
        boolean isTeleportInvulnerability()
        long getLoginAttackDelay()
        int getSignUsePerSecond()
        double getMaxFlySpeed()
        double getMaxWalkSpeed()
        int getMailsPerMinute()
        long getEconomyLagWarning()
        long getPermissionsLagWarning()
        void setEssentialsChatActive(boolean var1)
        long getMaxMute()
        long getMaxTempban()
        Map<String, Object> getListGroupConfig()
        int getMaxNickLength()
        boolean ignoreColorsInMaxLength()
        boolean hideDisplayNameInVanish()
        int getMaxUserCacheCount()
        long getMaxUserCacheValueExpiry()
        boolean allowSilentJoinQuit()
        boolean isCustomJoinMessage()
        String getCustomJoinMessage()
        boolean isCustomQuitMessage()
        String getCustomQuitMessage()
        String getCustomNewUsernameMessage()
        boolean isCustomNewUsernameMessage()
        boolean isCustomServerFullMessage()
        boolean isNotifyNoNewMail()
        boolean isDropItemsIfFull()
        boolean isLastMessageReplyRecipient()
        boolean isReplyToVanished()
        BigDecimal getMinimumPayAmount()
        boolean isPayExcludesIgnoreList()
        long getLastMessageReplyRecipientTimeout()
        boolean isMilkBucketEasterEggEnabled()
        boolean isSendFlyEnableOnJoin()
        boolean isWorldTimePermissions()
        boolean isSpawnOnJoin()
        List<String> getSpawnOnJoinGroups()
        boolean isUserInSpawnOnJoinGroup(IUser var1)
        boolean isTeleportToCenterLocation()
        boolean isCommandCooldownsEnabled()
        boolean isWorldChangeFlyResetEnabled()
        boolean isWorldChangePreserveFlying()
        boolean isWorldChangeSpeedResetEnabled()
        long getCommandCooldownMs(String var1)
        Entry<Pattern, Long> getCommandCooldownEntry(String var1)
        boolean isCommandCooldownPersistent(String var1)
        boolean isNpcsInBalanceRanking()
        NumberFormat getCurrencyFormat()
        List<EssentialsSign> getUnprotectedSignNames()
        boolean isKitAutoEquip()
        boolean isPastebinCreateKit()
        boolean isUseBetterKits()
        boolean isAllowBulkBuySell()
        boolean isAllowSellNamedItems()
        boolean isAddingPrefixInPlayerlist()
        boolean isAddingSuffixInPlayerlist()
        int getNotifyPlayerOfMailCooldown()
        int getMotdDelay()
        boolean isDirectHatAllowed()
        List<String> getDefaultEnabledConfirmCommands()
        boolean isConfirmCommandEnabledByDefault(String var1)
        ISettings.TeleportWhenFreePolicy getTeleportWhenFreePolicy()
        boolean isJailOnlineTime()
        boolean isCompassTowardsHomePerm()
        boolean isAllowWorldInBroadcastworld()
        String getItemDbType()
        boolean allowOldIdSigns()
        boolean isWaterSafe()
        boolean isSafeUsermap()
        boolean logCommandBlockCommands()
        Set<Predicate<String>> getNickBlacklist()
        double getMaxProjectileSpeed()
        boolean isRemovingEffectsOnHeal()
        boolean isSpawnIfNoHome()
        boolean isConfirmHomeOverwrite()
        boolean infoAfterDeath()
        boolean isRespawnAtBed()
        boolean isUpdateCheckEnabled()
        boolean showZeroBaltop()
        String getNickRegex()
        BigDecimal getMultiplier(User var1)
        int getMaxItemLore()
        Tag getPrimaryColor()
        Tag getSecondaryColor()
        BigDecimal getBaltopMinBalance()
        long getBaltopMinPlaytime()
    ITeleport class: net.ess3.api (extends com.earth2me.essentials.api.ITeleport) (deprecated)
        Instance Methods
        void now(Location var1, boolean var2, TeleportCause var3) (deprecated)
        void now(Player var1, boolean var2, TeleportCause var3) (deprecated)
        void teleport(Location var1, Trade var2) (deprecated)
        void teleport(Location var1, Trade var2, TeleportCause var3) (deprecated)
        void teleport(Player var1, Trade var2, TeleportCause var3) (deprecated)
        void teleportPlayer(IUser var1, Location var2, Trade var3, TeleportCause var4) (deprecated)
        void teleportPlayer(IUser var1, Player var2, Trade var3, TeleportCause var4) (deprecated)
        void respawn(Trade var1, TeleportCause var2) (deprecated)
        void warp(IUser var1, String var2, Trade var3, TeleportCause var4) (deprecated)
        void back(Trade var1) (deprecated)
        void back(IUser var1, Trade var2) (deprecated)
        void back() (deprecated)
    IUser class: net.ess3.api (extends com.earth2me.essentials.IUser) (deprecated)
        Instance Methods
        boolean isAuthorized(String var1)
        boolean isAuthorized(IEssentialsCommand var1)
        boolean isAuthorized(IEssentialsCommand var1, String var2)
        boolean isPermissionSet(String var1)
        void healCooldown()
        void giveMoney(BigDecimal var1)
        void giveMoney(BigDecimal var1, CommandSource var2)
        void payUser(User var1, BigDecimal var2)
        void takeMoney(BigDecimal var1)
        void takeMoney(BigDecimal var1, CommandSource var2)
        boolean canAfford(BigDecimal var1)
        Boolean canSpawnItem(Material var1)
        void setLastLocation()
        void setLogoutLocation()
        void requestTeleport(User var1, boolean var2)
        boolean hasOutstandingTeleportRequest() (deprecated, default)
        IAsyncTeleport getAsyncTeleport()
        BigDecimal getMoney()
        void setMoney(BigDecimal var1)
        void setAfk(boolean var1, Cause var2)
        boolean isHidden()
        boolean isLeavingHidden()
        void setLeavingHidden(boolean var1)
        void setHidden(boolean var1)
        boolean isGodModeEnabled()
        String getGroup()
        boolean inGroup(String var1)
        boolean canBuild()
        long getTeleportRequestTime() (deprecated)
        void enableInvulnerabilityAfterTeleport()
        void resetInvulnerabilityAfterTeleport()
        boolean hasInvulnerabilityAfterTeleport()
        boolean isVanished()
        void setVanished(boolean var1)
        boolean isIgnoreExempt()
        void sendMessage(String var1)
        void sendComponent(ComponentLike var1)
        Component tlComponent(String var1, Object... var2)
        String playerTl(String var1, Object... var2)
        void sendTl(String var1, Object... var2)
        Location getHome(String var1)
        Location getHome(Location var1)
        List<String> getHomes()
        void setHome(String var1, Location var2)
        void delHome(String var1)
        void renameHome(String var1, String var2)
        boolean hasHome()
        Location getLastLocation()
        Location getLogoutLocation()
        long getLastTeleportTimestamp()
        void setLastTeleportTimestamp(long var1)
        String getJail()
        void setJail(String var1)
        String getFormattedJailTime()
        long getLastActivityTime()
        List<String> getMails() (deprecated)
        void addMail(String var1) (deprecated)
        void sendMail(MailSender var1, String var2)
        void sendMail(MailSender var1, String var2, long var3)
        ArrayList<MailMessage> getMailMessages()
        void setMailList(ArrayList<MailMessage> var1)
        int getMailAmount()
        boolean isAfk()
        void setAfk(boolean var1) (deprecated)
        boolean isIgnoreMsg()
        void setIgnoreMsg(boolean var1)
        void setConfigProperty(String var1, Object var2) (deprecated)
        Set<String> getConfigKeys()
        Map<String, Object> getConfigMap()
        Map<String, Object> getConfigMap(String var1)
        Map<Pattern, Long> getCommandCooldowns() (deprecated)
        List<CommandCooldown> getCooldownsList()
        Date getCommandCooldownExpiry(String var1)
        void addCommandCooldown(Pattern var1, Date var2, boolean var3)
        boolean clearCommandCooldown(Pattern var1)
        Player getBase()
        CommandSource getSource()
        String getName()
        UUID getUUID()
        String getDisplayName()
        String getFormattedNickname()
        String getAfkMessage()
        void setAfkMessage(String var1)
        long getAfkSince()
        boolean isAcceptingPay()
        void setAcceptingPay(boolean var1)
        boolean isPromptingPayConfirm()
        void setPromptingPayConfirm(boolean var1)
        boolean isPromptingClearConfirm()
        void setPromptingClearConfirm(boolean var1)
        boolean isLastMessageReplyRecipient()
        void setLastMessageReplyRecipient(boolean var1)
        Map<User, BigDecimal> getConfirmingPayments()
        Block getTargetBlock(int var1)
        void setToggleShout(boolean var1)
        boolean isToggleShout()
        IUser.TpaRequest getNextTpaRequest(boolean var1, boolean var2, boolean var3)
        boolean hasPendingTpaRequests(boolean var1, boolean var2)
        List<String> getPastUsernames()
        void addPastUsername(String var1)
        boolean isFreeze()
        void setFreeze(boolean var1)
    IWarps class: net.ess3.api (extends com.earth2me.essentials.api.IWarps)
        Instance Methods
        Location getWarp(String var1)
        boolean isWarp(String var1)
        Collection<String> getList()
        int getCount()
        void removeWarp(String var1)
        void setWarp(String var1, Location var2)
        void setWarp(IUser var1, String var2, Location var3)
        UUID getLastOwner(String var1)
        boolean isEmpty()
        File getWarpFile(String var1) (deprecated)
    
    `
};