module.exports = {
    name: 'FactionsUUID',
    description: 'FactionsUUID is a Factions which brings the most popular factions functionality into the modern age, keeping as much original functionality intact as possible while adding some neat enhancements',
    pluginId: 'FactionsUUID',
    mavenIntegration: `
        <repositories>
            <repository>
              <id>dependency-download</id>
              <url>https://dependency.download/releases</url>
            </repository>
        </repositories>
        <dependencies>
            <dependency>
              <groupId>dev.kitteh</groupId>
              <artifactId>factionsuuid</artifactId>
              <version>0.7.0</version>
              <scope>provided</scope>
            </dependency>
        </dependencies>
    `,
    usage: `
        FPlayers class: com.massivecraft.factions
        Static Methods
        static com.massivecraft.factions.FPlayers getInstance()
        static com.massivecraft.factions.FPlayers getFPlayersImpl() (private)
        
        Abstract Methods
        abstract void clean()
        abstract Collection<com.massivecraft.factions.FPlayer> getOnlinePlayers()
        abstract com.massivecraft.factions.FPlayer getByPlayer(Player var1)
        abstract Collection<com.massivecraft.factions.FPlayer> getAllFPlayers()
        abstract void forceSave()
        abstract void forceSave(boolean var1)
        abstract com.massivecraft.factions.FPlayer getByOfflinePlayer(OfflinePlayer var1)
        abstract com.massivecraft.factions.FPlayer getById(String var1)
        abstract int load()
        
        FPlayer class: com.massivecraft.factions
        Here are all the methods in the FPlayer interface with their return types:
        Instance Methods
        
        void login()
        void logout()
        com.massivecraft.factions.Faction getFaction()
        String getFactionId() (deprecated)
        int getFactionIntId()
        boolean hasFaction()
        void setFaction(com.massivecraft.factions.Faction var1)
        boolean willAutoLeave()
        void setAutoLeave(boolean var1)
        long getLastFrostwalkerMessage()
        void setLastFrostwalkerMessage()
        void setMonitorJoins(boolean var1)
        boolean isMonitoringJoins()
        com.massivecraft.factions.perms.Role getRole()
        void setRole(com.massivecraft.factions.perms.Role var1)
        boolean shouldTakeFallDamage()
        void setTakeFallDamage(boolean var1)
        double getPowerBoost()
        void setPowerBoost(double var1)
        com.massivecraft.factions.Faction getAutoClaimFor()
        void setAutoClaimFor(com.massivecraft.factions.Faction var1)
        com.massivecraft.factions.Faction getAutoUnclaimFor()
        void setAutoUnclaimFor(com.massivecraft.factions.Faction var1)
        boolean isAutoSafeClaimEnabled() (deprecated)
        void setIsAutoSafeClaimEnabled(boolean var1) (deprecated)
        boolean isAutoWarClaimEnabled() (deprecated)
        void setIsAutoWarClaimEnabled(boolean var1) (deprecated)
        boolean isAdminBypassing()
        boolean isVanished()
        void setIsAdminBypassing(boolean var1)
        void setChatMode(com.massivecraft.factions.struct.ChatMode var1)
        com.massivecraft.factions.struct.ChatMode getChatMode()
        void setIgnoreAllianceChat(boolean var1)
        boolean isIgnoreAllianceChat()
        void setSpyingChat(boolean var1)
        boolean isSpyingChat()
        boolean showScoreboard()
        void setShowScoreboard(boolean var1)
        void resetFactionData(boolean var1)
        void resetFactionData()
        long getLastLoginTime()
        void setLastLoginTime(long var1)
        boolean isMapAutoUpdating()
        void setMapAutoUpdating(boolean var1)
        boolean hasLoginPvpDisabled()
        com.massivecraft.factions.FLocation getLastStoodAt()
        void setLastStoodAt(com.massivecraft.factions.FLocation var1)
        String getTitle()
        void setTitle(CommandSender var1, String var2)
        String getName()
        String getTag()
        String getNameAndSomething(String var1)
        String getNameAndTitle()
        String getNameAndTag()
        String getNameAndTitle(com.massivecraft.factions.Faction var1)
        String getNameAndTitle(com.massivecraft.factions.FPlayer var1)
        String getChatTag()
        String getChatTag(com.massivecraft.factions.Faction var1)
        String getChatTag(com.massivecraft.factions.FPlayer var1)
        int getKills()
        int getDeaths()
        com.massivecraft.factions.perms.Relation getRelationToLocation()
        void heal(int var1)
        double getPower()
        void alterPower(double var1)
        double getPowerMax()
        double getPowerMin()
        int getPowerRounded()
        int getPowerMaxRounded()
        int getPowerMinRounded()
        void updatePower()
        void losePowerFromBeingOffline()
        void onDeath()
        boolean isInOwnTerritory()
        boolean isInOthersTerritory()
        boolean isInAllyTerritory()
        boolean isInNeutralTerritory()
        boolean isInEnemyTerritory()
        void sendFactionHereMessage(com.massivecraft.factions.Faction var1)
        void leave(boolean var1)
        boolean canClaimForFaction(com.massivecraft.factions.Faction var1)
        boolean canClaimForFactionAtLocation(com.massivecraft.factions.Faction var1, Location var2, boolean var3) (deprecated)
        boolean canClaimForFactionAtLocation(com.massivecraft.factions.Faction var1, com.massivecraft.factions.FLocation var2, boolean var3)
        boolean attemptClaim(com.massivecraft.factions.Faction var1, Location var2, boolean var3)
        boolean attemptClaim(com.massivecraft.factions.Faction var1, com.massivecraft.factions.FLocation var2, boolean var3)
        boolean attemptUnclaim(com.massivecraft.factions.Faction var1, com.massivecraft.factions.FLocation var2, boolean var3)
        String getId()
        Player getPlayer()
        boolean isOnline()
        void sendMessage(String var1)
        void sendMessage(List<String> var1)
        int getMapHeight()
        void setMapHeight(int var1)
        boolean isOnlineAndVisibleTo(Player var1)
        void remove()
        boolean isOffline()
        void setId(String var1)
        void flightCheck()
        boolean isFlying()
        void setFlying(boolean var1)
        void setFlying(boolean var1, boolean var2)
        boolean isAutoFlying()
        void setAutoFlying(boolean var1)
        boolean canFlyAtLocation()
        boolean canFlyAtLocation(com.massivecraft.factions.FLocation var1)
        boolean canFlyInFactionTerritory(com.massivecraft.factions.Faction faction) (deprecated, default)
        boolean isSeeingChunk()
        void setSeeingChunk(boolean var1)
        boolean getFlyTrailsState()
        void setFlyTrailsState(boolean var1)
        String getFlyTrailsEffect()
        void setFlyTrailsEffect(String var1)
        boolean isWarmingUp()
        com.massivecraft.factions.util.WarmUpUtil.Warmup getWarmupType()
        void addWarmup(com.massivecraft.factions.util.WarmUpUtil.Warmup var1, int var2)
        void stopWarmup()
        void clearWarmup()
        void setOfflinePlayer(Player var1)
        
        FLocation class: com.massivecraft.factions
        Constructors
        FLocation()
        FLocation(String worldName, int x, int z)
        FLocation(Location location)
        FLocation(Chunk chunk)
        FLocation(Player player)
        FLocation(com.massivecraft.factions.FPlayer fplayer)
        FLocation(Block block)
        
        Static Methods
        static com.massivecraft.factions.FLocation fromString(String string)
        static int blockToChunk(int blockVal)
        static int blockToRegion(int blockVal)
        static int chunkToRegion(int chunkVal)
        static int chunkToBlock(int chunkVal)
        static int regionToBlock(int regionVal)
        static int regionToChunk(int regionVal)
        static HashSet<com.massivecraft.factions.FLocation> getArea(com.massivecraft.factions.FLocation from, com.massivecraft.factions.FLocation to)
        
        Instance Methods
        String getWorldName()
        World getWorld()
        long getX()
        long getZ()
        String getCoordString()
        Chunk getChunk()
        String toString()
        com.massivecraft.factions.FLocation getRelative(int dx, int dz)
        double getDistanceTo(com.massivecraft.factions.FLocation that)
        double getDistanceSquaredTo(com.massivecraft.factions.FLocation that)
        boolean isInChunk(Location loc)
        boolean isOutsideWorldBorder(int buffer)
        Set<com.massivecraft.factions.FLocation> getCircle(double radius)
        int hashCode()
        boolean equals(Object obj)
        
        Factions class: com.massivecraft.factions
        Here are all the methods in the Factions class with their return types:
        Static Methods
        static com.massivecraft.factions.Factions getInstance()
        static com.massivecraft.factions.Factions getFactionsImpl() (private)
        
        Abstract Methods
        abstract com.massivecraft.factions.Faction getFactionById(String var1) (deprecated)
        abstract com.massivecraft.factions.Faction getFactionById(int var1)
        abstract com.massivecraft.factions.Faction getByTag(String var1)
        abstract com.massivecraft.factions.Faction getBestTagMatch(String var1)
        abstract boolean isTagTaken(String var1)
        abstract boolean isValidFactionId(String var1) (deprecated)
        abstract boolean isValidFactionId(int var1)
        abstract com.massivecraft.factions.Faction createFaction()
        abstract void removeFaction(String var1) (deprecated)
        abstract void removeFaction(com.massivecraft.factions.Faction var1)
        abstract Set<String> getFactionTags()
        abstract ArrayList<com.massivecraft.factions.Faction> getAllFactions()
        abstract com.massivecraft.factions.Faction getWilderness()
        abstract com.massivecraft.factions.Faction getSafeZone()
        abstract com.massivecraft.factions.Faction getWarZone()
        abstract void forceSave()
        abstract void forceSave(boolean var1)
        abstract int load()
        
        Instance Methods
        com.massivecraft.factions.Faction getNone() (deprecated)
        
        Faction class: com.massivecraft.factions
        Instance Methods
        Map<String, List<String>> getAnnouncements()
        Map<String, com.massivecraft.factions.util.LazyLocation> getWarps()
        com.massivecraft.factions.util.LazyLocation getWarp(String var1)
        void setWarp(String var1, com.massivecraft.factions.util.LazyLocation var2)
        boolean isWarp(String var1)
        boolean hasWarpPassword(String var1)
        boolean isWarpPassword(String var1, String var2)
        void setWarpPassword(String var1, String var2)
        boolean removeWarp(String var1)
        void clearWarps()
        int getMaxVaults()
        void setMaxVaults(int var1)
        void addAnnouncement(com.massivecraft.factions.FPlayer var1, String var2)
        void sendUnreadAnnouncements(com.massivecraft.factions.FPlayer var1)
        void removeAnnouncements(com.massivecraft.factions.FPlayer var1)
        Set<String> getInvites()
        String getId() (deprecated)
        int getIntId()
        void invite(com.massivecraft.factions.FPlayer var1)
        void deinvite(com.massivecraft.factions.FPlayer var1)
        boolean isInvited(com.massivecraft.factions.FPlayer var1)
        void ban(com.massivecraft.factions.FPlayer var1, com.massivecraft.factions.FPlayer var2)
        void unban(com.massivecraft.factions.FPlayer var1)
        boolean isBanned(com.massivecraft.factions.FPlayer var1)
        Set<com.massivecraft.factions.struct.BanInfo> getBannedPlayers()
        boolean getOpen()
        void setOpen(boolean var1)
        boolean isPeaceful()
        void setPeaceful(boolean var1)
        void setPeacefulExplosionsEnabled(boolean var1)
        boolean getPeacefulExplosionsEnabled()
        boolean noExplosionsInTerritory()
        boolean isPermanent()
        void setPermanent(boolean var1)
        String getTag()
        String getTag(String var1)
        String getTag(com.massivecraft.factions.Faction var1)
        String getTag(com.massivecraft.factions.FPlayer var1)
        void setTag(String var1)
        String getComparisonTag()
        String getDescription()
        void setDescription(String var1)
        String getLink()
        void setLink(String var1)
        void setHome(Location var1)
        void delHome()
        boolean hasHome()
        Location getHome()
        long getFoundedDate()
        void setFoundedDate(long var1)
        void confirmValidHome()
        boolean noPvPInTerritory()
        boolean noMonstersInTerritory()
        boolean isNormal()
        boolean isNone() (deprecated, default)
        boolean isWilderness()
        boolean isSafeZone()
        boolean isWarZone()
        boolean isPlayerFreeType()
        void setLastDeath(long var1)
        int getKills()
        int getDeaths()
        boolean hasAccess(com.massivecraft.factions.perms.Selectable var1, com.massivecraft.factions.perms.PermissibleAction var2, com.massivecraft.factions.FLocation var3)
        int getLandRounded()
        int getLandRoundedInWorld(String var1)
        int getTNTBank()
        void setTNTBank(int var1)
        com.massivecraft.factions.perms.Relation getRelationWish(com.massivecraft.factions.Faction var1)
        void setRelationWish(com.massivecraft.factions.Faction var1, com.massivecraft.factions.perms.Relation var2)
        int getRelationCount(com.massivecraft.factions.perms.Relation var1)
        double getDTR()
        double getDTRWithoutUpdate()
        void setDTR(double var1)
        long getLastDTRUpdateTime()
        long getFrozenDTRUntilTime()
        void setFrozenDTR(long var1)
        boolean isFrozenDTR()
        double getPower()
        double getPowerMax()
        int getPowerRounded()
        int getPowerMaxRounded()
        Integer getPermanentPower()
        void setPermanentPower(Integer var1)
        boolean hasPermanentPower()
        double getPowerBoost()
        void setPowerBoost(double var1)
        boolean hasLandInflation()
        boolean isPowerFrozen()
        void refreshFPlayers()
        boolean addFPlayer(com.massivecraft.factions.FPlayer var1)
        boolean removeFPlayer(com.massivecraft.factions.FPlayer var1)
        int getSize()
        Set<com.massivecraft.factions.FPlayer> getFPlayers()
        Set<com.massivecraft.factions.FPlayer> getFPlayersWhereOnline(boolean var1)
        Set<com.massivecraft.factions.FPlayer> getFPlayersWhereOnline(boolean var1, com.massivecraft.factions.FPlayer var2)
        com.massivecraft.factions.FPlayer getFPlayerAdmin()
        List<com.massivecraft.factions.FPlayer> getFPlayersWhereRole(com.massivecraft.factions.perms.Role var1)
        List<Player> getOnlinePlayers()
        boolean hasPlayersOnline()
        void memberLoggedOff()
        void promoteNewLeader()
        com.massivecraft.factions.perms.Role getDefaultRole()
        void setDefaultRole(com.massivecraft.factions.perms.Role var1)
        void sendMessage(String var1)
        void sendMessage(List<String> var1)
        Map<com.massivecraft.factions.FLocation, Set<String>> getClaimOwnership()
        void clearAllClaimOwnership()
        void clearClaimOwnership(com.massivecraft.factions.FLocation var1)
        void clearClaimOwnership(com.massivecraft.factions.FPlayer var1)
        int getCountOfClaimsWithOwners()
        boolean doesLocationHaveOwnersSet(com.massivecraft.factions.FLocation var1)
        boolean isPlayerInOwnerList(com.massivecraft.factions.FPlayer var1, com.massivecraft.factions.FLocation var2)
        void setPlayerAsOwner(com.massivecraft.factions.FPlayer var1, com.massivecraft.factions.FLocation var2)
        void removePlayerAsOwner(com.massivecraft.factions.FPlayer var1, com.massivecraft.factions.FLocation var2)
        Set<String> getOwnerList(com.massivecraft.factions.FLocation var1)
        String getOwnerListString(com.massivecraft.factions.FLocation var1)
        boolean playerHasOwnershipRights(com.massivecraft.factions.FPlayer var1, com.massivecraft.factions.FLocation var2)
        void remove()
        Set<com.massivecraft.factions.FLocation> getAllClaims()
        
        Board class: com.massivecraft.factions
        Static Methods
        static com.massivecraft.factions.Board getInstance()
        static com.massivecraft.factions.Board getBoardImpl() (private)
        
        Abstract Methods
        abstract String getIdAt(com.massivecraft.factions.FLocation var1)
        abstract int getIntIdAt(com.massivecraft.factions.FLocation var1)
        abstract com.massivecraft.factions.Faction getFactionAt(com.massivecraft.factions.FLocation var1)
        abstract void setIdAt(String var1, com.massivecraft.factions.FLocation var2) (deprecated)
        abstract void setFactionAt(com.massivecraft.factions.Faction var1, com.massivecraft.factions.FLocation var2)
        abstract void removeAt(com.massivecraft.factions.FLocation var1)
        abstract Set<com.massivecraft.factions.FLocation> getAllClaims(String var1) (deprecated)
        abstract Set<com.massivecraft.factions.FLocation> getAllClaims(com.massivecraft.factions.Faction var1)
        abstract void clearOwnershipAt(com.massivecraft.factions.FLocation var1)
        abstract void unclaimAll(String var1) (deprecated)
        abstract void unclaimAll(com.massivecraft.factions.Faction var1)
        abstract void unclaimAllInWorld(String var1, World var2) (deprecated)
        abstract void unclaimAllInWorld(com.massivecraft.factions.Faction var1, World var2)
        abstract boolean isBorderLocation(com.massivecraft.factions.FLocation var1)
        abstract boolean isConnectedLocation(com.massivecraft.factions.FLocation var1, com.massivecraft.factions.Faction var2)
        abstract boolean hasFactionWithin(com.massivecraft.factions.FLocation var1, com.massivecraft.factions.Faction var2, int var3)
        abstract void clean()
        abstract int getFactionCoordCount(String var1) (deprecated)
        abstract int getFactionCoordCount(com.massivecraft.factions.Faction var1)
        abstract int getFactionCoordCountInWorld(com.massivecraft.factions.Faction var1, String var2)
        abstract List<Component> getMap(com.massivecraft.factions.FPlayer var1, com.massivecraft.factions.FLocation var2, double var3)
        abstract void forceSave()
        abstract void forceSave(boolean var1)
        abstract int load()
    `
};